# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [19]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

# Let's define a one-dimensional array 

import numpy as np

list_1 = [50, 60, 80, 100, 500, 600]

list_1

[50, 60, 80, 100, 500, 600]

In [20]:
# Let's create a numpy array from the list "my_list"
my_numpy_array = np.array(list_1)
my_numpy_array

array([ 50,  60,  80, 100, 500, 600])

In [21]:
type(my_numpy_array)

numpy.ndarray

In [22]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array([[2, 5, 8], [7, 3, 6]])
my_matrix

array([[2, 5, 8],
       [7, 3, 6]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [23]:
x = np.array([[3, 7, 9, 3], [4, 3, 2, 2]])
x

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [24]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(20)
x

array([0.11679494, 0.07062876, 0.86572123, 0.11597921, 0.70250389,
       0.05640011, 0.05503009, 0.87040491, 0.2180006 , 0.6270327 ,
       0.13442633, 0.35219372, 0.35938991, 0.16109594, 0.82311556,
       0.48659716, 0.46286786, 0.35177683, 0.03098666, 0.86946132])

In [25]:
# you can create a matrix of random number as well
x = np.random.rand(3, 3)
x

array([[0.45293422, 0.00375854, 0.43287045],
       [0.80997476, 0.60608119, 0.03881077],
       [0.43539553, 0.92141588, 0.07486616]])

In [26]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 50)
x

46

In [27]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1, 100, 15)
x

array([57,  1,  9, 56, 72, 84,  4, 15, 87, 54, 96, 28, 21, 94, 34])

In [28]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1, 30)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [30]:
# Matrix of ones
x = np.ones((7,7))
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [31]:
# Array of zeros
x = np.zeros(8)
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [32]:
x = int(input("Please enter a positive value"))
randoms = np.random.randint(1, x, 10)
randoms

array([18, 15, 16, 44, 15, 12, 21, 23, 36, 35])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [33]:
# np.arrange() returns an evenly spaced values within a given interval
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# Add 2 numpy arrays together
sum_numbers = x + y
sum_numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
squared = x ** 2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [37]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [39]:
x = np.array([5, 7, 20])
y = np.array([9, 15, 4])

distance = y - x
distance

array([  4,   8, -16])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [40]:
my_numpy_array = np.array([3, 5, 6, 2, 8, 10, 20, 50])
my_numpy_array

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [41]:
# Access specific index from the numpy array
my_numpy_array[-1]

np.int64(50)

In [42]:
# Starting from the first index 0 up until and NOT including the last element
my_numpy_array[0:3]

array([3, 5, 6])

In [43]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_array[0:4] = 7
my_numpy_array

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [44]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1, 10, (4, 4))
matrix

array([[4, 1, 4, 8],
       [9, 9, 8, 9],
       [9, 8, 2, 1],
       [6, 5, 2, 1]])

In [45]:
# Get a row from a matrix
matrix[-1]

array([6, 5, 2, 1])

In [46]:
# Get one element
matrix[0][2]

np.int64(4)

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [47]:
x = np.array([[2, 30, 20, -2, -4],
              [3, 4, 40, -3, -2],
              [-3, 4, -6, 90, 10],
              [25, 45, 34, 22, 12],
              [13, 24, 22, 32, 37]])
x[-1] = 0
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [48]:
matrix = np.random.randint(1, 10, (5, 5))
matrix

array([[7, 3, 3, 1, 1],
       [1, 5, 7, 6, 7],
       [8, 2, 2, 7, 3],
       [9, 6, 4, 4, 8],
       [3, 9, 3, 5, 2]])

In [49]:
new_matrix = matrix[ matrix > 7]
new_matrix

array([8, 9, 8, 9])

In [50]:
# Obtain odd elements only
new_matrix = matrix[ matrix % 2 == 1]
new_matrix

array([7, 3, 3, 1, 1, 1, 5, 7, 7, 7, 3, 9, 3, 9, 3, 5])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [51]:
x = np.array([[2, 30, 20, -2, -4],
             [3, 4, 40, -3, -2],
             [-3, 4, -6, 90, 10],
             [25, 45, 34, 22, 12],
             [13, 24, 22, 32, 37]])
x[x < 0] = 0
x[x % 2 == 1] = -2
x

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [52]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [1]:
import pandas as pd

In [2]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary

bank_client_df = pd.DataFrame({'Bank Client Id': [111, 222, 333, 444],
                               'Bank Client Name': ['Chanel', 'Steve', 'Jacob', 'Roger'],
                               'Net Worth [$]': [4500, 5000, 9000, 3700],
                               'Years With Bank': [4, 8, 4, 5]})

bank_client_df

Bank Client Id Bank Client Name  Net Worth [$]  Years With Bank
0             111           Chanel           4500                4
1             222            Steve           5000                8
2             333            Jacob           9000                4
3             444            Roger           3700                5

In [3]:
# Let's obtain the data type 
type(bank_client_df)

pandas.core.frame.DataFrame

In [4]:
# you can only view the first couple of rows using .head()
bank_client_df.head(2)

Bank Client Id Bank Client Name  Net Worth [$]  Years With Bank
0             111           Chanel           4500                4
1             222            Steve           5000                8

In [5]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(2)

Bank Client Id Bank Client Name  Net Worth [$]  Years With Bank
2             333            Jacob           9000                4
3             444            Roger           3700                5

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [6]:
portfolio_df = pd.DataFrame({'Ticker Symbol': ['AMZN', 'GOOG', 'AAPL'],
                             'Number of Shares': [5, 3, 4],
                             'Price per Share': [150, 200, 300]})

stocks_dollar_value = portfolio_df['Number of Shares'] * portfolio_df['Price per Share']
stocks_dollar_value.sum()

np.int64(2550)

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [7]:
# Pandas is used to read a csv file and store data in a DataFrame

house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
house_price_df[0]

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [91]:
house_price_df[1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

In [ ]:
# Read tabular data using read_html


MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html

In [ ]:
%%sql


In [93]:
us_retirement_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
us_retirement_df[0]

HTTPError: HTTP Error 403: Forbidden

# TASK #8: PANDAS OPERATIONS

In [8]:
# Let's define a dataframe as follows:

bank_client_df = pd.DataFrame({'Bank Client Id': [111, 222, 333, 444],
                               'Bank Client Name': ['Chanel', 'Steve', 'Jacob', 'Roger'],
                               'Net Worth [$]': [4500, 5000, 9000, 3700],
                               'Years With Bank': [4, 8, 4, 5]})

bank_client_df

Bank Client Id Bank Client Name  Net Worth [$]  Years With Bank
0             111           Chanel           4500                4
1             222            Steve           5000                8
2             333            Jacob           9000                4
3             444            Roger           3700                5

In [96]:
# Pick certain rows that satisfy a certain criteria 
df_loyal = bank_client_df[ bank_client_df['Years With Bank'] > 4 ]
df_loyal


Bank Client Id Bank Client Name  Net Worth [$]  Years With Bank
1             222            Steve           5000                8
3             444            Roger           3700                5

In [100]:
# Delete a column from a DataFrame
del bank_client_df['Bank Client Id']
bank_client_df

Bank Client Name  Net Worth [$]  Years With Bank
0           Chanel           4500                4
1            Steve           5000                8
2            Jacob           9000                4
3            Roger           3700                5

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [113]:
df_high_networth = bank_client_df[bank_client_df['Net Worth [$]'] >= 5000]

print(df_high_networth)

df_high_networth['Net Worth [$]'].sum()

  Bank Client Name  Net Worth [$]  Years With Bank
1            Steve           5000                8
2            Jacob           9000                4


np.int64(14000)

# TASK #9: PANDAS WITH FUNCTIONS

In [117]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net Worth [$]':[3500, 29000, 10000, 2000],
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [115]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def networth_update(balance):
    return balance * 1.2

In [119]:
# You can apply a function to the DataFrame 
bank_client_df['Net Worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net Worth [$], dtype: float64

In [123]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [134]:
def triple_stock_prices(price):
    return (price * 3) + 200

updated_balances = bank_client_df['Net Worth [$]'].apply(triple_stock_prices)
updated_balances.sum()

np.int64(134300)

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [9]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [10]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by= 'Years with bank')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [11]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [12]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df.sort_values("Years with bank", inplace=True)

In [13]:
# Note that now the change (ordering) took place 
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [ ]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [19]:
df = pd.DataFrame({'A':  ['A0', 'A1', 'A2', 'A3'],
                   'B': ['B0', 'B1', 'B2', 'B3'],
                   'C': ['C0', 'C1', 'C2', 'C3'],
                   'D': ['D0', 'D1', 'D2', 'D3']})
df

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [18]:
df1 = pd.DataFrame({'A':  ['A4', 'A5', 'A6', 'A7'],
                   'B': ['B4', 'B5', 'B6', 'B7'],
                   'C': ['C4', 'C5', 'C6', 'C7'],
                   'D': ['D4', 'D5', 'D6', 'D7']})
df1

A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [21]:
pd.concat([df, df1])

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [32]:
Bank_df_1 = pd.DataFrame({'Id': [1, 2, 3, 4, 5],
                               'Name': ['Chanel', 'Steve', 'Mitch', 'Ryan', 'Lucie'],
                               'Last Name': ['Rodriguez', 'Sanchez', 'McGreggor', 'Cabello', 'Martin']})

Bank_df_2 = pd.DataFrame({'Id': [6, 7, 8, 9, 10],
                               'Name': ['Michelle', 'Trevor', 'Michael', 'Jack', 'Ludwig'],
                               'Last Name': ['Tucson', 'Phillips', 'Mayers', 'Sparrow', 'Beethoveen']})

Bank_clients_df = pd.concat([Bank_df_1, Bank_df_2])

Salary_information = pd.DataFrame({'Id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                                    'Salary': [1800, 2100, 1900, 1350, 1400, 1500, 1400, 1480, 1790, 1680]})

Bank_clients_df = pd.merge(Bank_clients_df, Salary_information, on='Id', how='left')

my_bank_client = pd.DataFrame({'Id': [14], 'Name': ['Amaury'], 'Last Name': ['Paillart'], 'Salary': [3800]})

Bank_clients_df = pd.concat([Bank_clients_df, my_bank_client])

Bank_clients_df

Id      Name   Last Name  Salary
0   1    Chanel   Rodriguez    1800
1   2     Steve     Sanchez    2100
2   3     Mitch   McGreggor    1900
3   4      Ryan     Cabello    1350
4   5     Lucie      Martin    1400
5   6  Michelle      Tucson    1500
6   7    Trevor    Phillips    1400
7   8   Michael      Mayers    1480
8   9      Jack     Sparrow    1790
9  10    Ludwig  Beethoveen    1680
0  14    Amaury    Paillart    3800

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

MINI CHALLENGE #1 SOLUTION: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [ ]:
x = np.array([[[3, 7, 9, 3] , [4, 3, 2, 2]]])
x

MINI CHALLENGE #2 SOLUTION:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 10)
x

MINI CHALLENGE #3 SOLUTION:
- Given the X and Y values below, obtain the distance between them


```
X = [5, 7, 20]
Y = [9, 15, 4]
```




In [ ]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

MINI CHALLENGE #4 SOLUTION:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

MINI CHALLENGE #5 SOLUTION:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X<0] = 0
X[X%2==1] = -2
X

MINI CHALLENGE #6 SOLUTION:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [ ]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40], 
                             'Number of stocks':[3, 4, 9]})
portfolio_df

In [ ]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

MINI CHALLENGE #7 SOLUTION:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [ ]:
# Read tabular data using read_html
retirement_age_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_age_df

MINI CHALLENGE #8 SOLUTION:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
df_high_networth = bank_client_df[ (bank_client_df['Net worth [$]'] >= 5000) ]
df_high_networth

In [ ]:
df_high_networth['Net worth [$]'].sum()

MINI CHALLENGE #9 SOLUTION:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [ ]:
def networth_update(balance):
    return balance * 3 + 200 

In [ ]:
# You can apply a function to the DataFrame 
results = bank_client_df['Net worth [$]'].apply(networth_update)
results

In [ ]:
results.sum()

PROJECT SOLUTION:

In [ ]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all


In [ ]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

In [ ]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df